import cors from 'cors';
import express from 'express';
import teamsRouter from './routes/teams';
import conferencesRouter from './routes/conferences';
import playersRouter from './routes/players';
import coachesRouter from './routes/coaches';
import recruitsRouter from './routes/recruits';
import rankingsRouter from './routes/rankings';
import searchRouter from './routes/search';
import recruitingRouter from './routes/recruiting';
import portalRouter from './routes/portal';
import nilRouter from './routes/nil';
import tamperingRouter from './routes/tampering';
import gameRouter from './routes/game';
import coachingPhase3Router from './routes/coaching';
import playstyleRouter from './routes/playstyle';
import moraleRouter from './routes/morale';
import seasonRouter from './routes/season';
import scheduleRouter from './routes/schedule';
import standingsRouter from './routes/standings';
import postseasonRouter from './routes/postseason';

const app = express();
app.use(cors());
app.use(express.json());

app.get('/api/health', (_req, res) => res.json({ ok: true }));
app.use('/api/teams', teamsRouter);
app.use('/api/conferences', conferencesRouter);
app.use('/api/players', playersRouter);
app.use('/api/coaches', coachesRouter);
app.use('/api/recruits', recruitsRouter);
app.use('/api/rankings', rankingsRouter);
app.use('/api/search', searchRouter);
app.use('/api/recruiting', recruitingRouter);
app.use('/api/portal', portalRouter);
app.use('/api/nil', nilRouter);
app.use('/api/tampering', tamperingRouter);
app.use('/api/game', gameRouter);
app.use('/api/coaching', coachingPhase3Router);
app.use('/api/playstyle', playstyleRouter);
app.use('/api/morale', moraleRouter);
app.use('/api/season', seasonRouter);
app.use('/api/schedule', scheduleRouter);
app.use('/api/standings', standingsRouter);
app.use('/api/postseason', postseasonRouter);

const port = Number(process.env.PORT ?? 4000);
app.listen(port, () => {
  console.log(`API listening on http://localhost:${port}`);
});
